### ISSUE TITLE
Support additional SSH key exchange algorithms

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/diego-ssh#43]
In our review of secure cryptographic key exchanges, we found that only curve 25519 is used in our implementation (other options use sha1) in Diego due to https://github.com/golang/go/issues/17230

This presents a problem because this curve is not a standard and is not yet approved for FIPS compliance.  Almost all clients universally support diffie-hellman-group-exchange-sha256 however golang itself does not.  This forces users of Diego who wish to SSH to add cyphers which do not meet their security requirements, and server operators to use insecure key exchange algorithms. 

One potential solution would be to use a openssh based approach over a golang approach.  Another would be to contribute a patch upstream to golang, however they have been unable to move forward since 2016.

**Comment by emalm** [comment]
Hi, @sharms, can you please provide a reference to the set of key-exchange algorithms that are FIPS compliant? In particular, do they include any of the `ecdh-sha2-nistp{256,384,521}` algorithms? Those ones don't use SHA1 but are [already implemented](https://github.com/golang/crypto/blob/2b6c08872f4b66da917bb4ce98df4f0307330f78/ssh/common.go#L50) in the `golang.org/x/crypto/ssh` library, so they might be both suitable for your use and available today via the [`diego.ssh_proxy.allowed_keyexchanges ` BOSH property](https://github.com/cloudfoundry/diego-release/blob/v2.4.0/jobs/ssh_proxy/spec#L47) on the `ssh_proxy` job.

Thanks,
Eric, CF Diego PM

**Comment by sharms** [comment]
Hi Eric - trying to wrangle a few different sets of standards to make a recommendation.   Reviewing the IETF proposed updates[1]:

* **diffie-hellman-group-exchange-sha256**: "This method MUST be implemented." 
* **ECDH algorithms**: "this curve may not be as useful and strong as desired for handling TOP SECRET information"

Additionally, **diffie-hellman-group-exchange-sha256** is specified as allowable by both SUSE and Ubuntu FIPS 140-2 compliant mode implementations[2][3].

The problem we are aiming to solve is that we do not control the clients or libraries, however if they implement the standard, Diego SSH should allow them to communicate.  After reviewing the recommendations it is understandable with the concerns presented around ECDH that administrators and product vendors would choose a conservative algorithm such as Diffie Hellman Group Exchange, and this is allowable under my highly novice interpretation of the standards.

[1] https://tools.ietf.org/html/draft-ietf-curdle-ssh-kex-sha2-10#page-6
[2] https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2472.pdf
[3] https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2906.pdf

**Comment by emalm** [comment]
Thanks for the additional references, @sharms, especially the NIST security policy documents. From the [SLES 12 OpenSSH Server](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2471.pdf) and [Ubuntu OpenSSH Server](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2906.pdf) policy documents, it looks like they do recommend the `ecdh-sha2-nistp` set of key-exchange algorithms, and the SLES 12 server policy document is even more explicit about recommending 

> a subset out of "diffie-hellman-group14-sha1, diffie-hellman-group-exchange-sha1, diffie-hellman-group-exchange-sha256, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521"

as the set to configure for the `KexAlgorithms` parameter in the `sshd` config. Based on that, it sounds like it would be acceptable for FIPS 140-2 compliance to support only that `ecdh-sha2-nistp` set of algorithms, and clients can negotiate to those. I don't think it's required that every server support every recommended algorithm: that's why there's a negotiation process as part of the SSH protocol handshake.

Also, I don't see the "MUST" recommendation for diffie-hellman-group-exchange-sha256 in https://tools.ietf.org/html/draft-ietf-curdle-ssh-kex-sha2-10 (which is also still in draft status and still seems to be undergoing periodic revision). In fact, according to its [section 5](https://tools.ietf.org/html/draft-ietf-curdle-ssh-kex-sha2-10#section-5), the only "MUST" recommendation is diffie-hellman-group14-sha256, and diffie-hellman-group-exchange-sha256 is merely a "MAY" recommendation elsewhere in the document (and is oddly absent from that table &mdash; maybe they'll correct that in draft 11).

Thanks again,
Eric

**Comment by emalm** [comment]
Hey, @sharms, since the SSH proxy can use other key-exchange algorithms that do comply with FIPS, I'll close this out. We'll certainly add support for diffie-hellman-group-exchange-sha256 if it becomes available in the underlying Golang SSH library.

Thanks again,
Eric
